# -*- coding: utf-8 -*-
"""Generate UF4 icon resources from Resources/Icons/assets."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ICON_ROOT = ROOT / "Resources" / "Icons"
ASSET_ROOT = ICON_ROOT / "assets"
BUILD_ROOT = ICON_ROOT / "svg"
QRC_PATH = ICON_ROOT / "uf4_icons.qrc"
ICON_PY_PATH = ROOT / "App" / "Core" / "icons.py"

FILL_RE = re.compile(r'fill="(?!none")[^"]*"')
STYLE_FILL_RE = re.compile(r"fill:\s*(?!none\b)[^;\"']+")
VALID_NAME_RE = re.compile(r"[^0-9A-Za-z_]+")

EMBEDDED_ICON_NAMES = {
    "Arrow Download",
    "Battery 0",
    "Battery 1",
    "Battery 2",
    "Battery 3",
    "Battery 4",
    "Battery 5",
    "Battery 6",
    "Battery 7",
    "Battery 8",
    "Battery 9",
    "Battery 10",
    "Battery Charge",
    "Battery Checkmark",
    "Battery Saver",
    "Battery Warning",
    "Bluetooth",
    "Bluetooth Connected",
    "Bluetooth Disabled",
    "Bluetooth Searching",
    "Board",
    "Brain Circuit",
    "Cellular 3G",
    "Cellular 4G",
    "Cellular 5G",
    "Cellular Data 1",
    "Cellular Data 2",
    "Cellular Data 3",
    "Cellular Data 4",
    "Cellular Data 5",
    "Cellular Off",
    "Cellular Warning",
    "Cloud Arrow Down",
    "Connected",
    "Connector",
    "Developer Board",
    "Developer Board Search",
    "Flash",
    "Flash Auto",
    "Flash Checkmark",
    "Flash Flow",
    "Flash Off",
    "Flash Settings",
    "Flash Sparkle",
    "Gauge",
    "Hard Drive",
    "IoT",
    "IoT Alert",
    "Plug Connected",
    "Plug Connected Settings",
    "Plug Disconnected",
    "Port HDMI",
    "Port Micro USB",
    "Port USB A",
    "Port USB C",
    "Power",
    "Router",
    "Router Off",
    "Save",
    "Save Arrow Right",
    "Save Sync",
    "Serial Port",
    "Serial Port Off",
    "Server",
    "Storage",
    "Temperature",
    "Toolbox",
    "Top Speed",
    "USB",
    "USB Off",
    "USB Plug",
    "Usb Stick",
    "Warning",
    "WiFi 1",
    "WiFi 2",
    "WiFi 3",
    "WiFi 4",
    "WiFi Lock",
    "WiFi Off",
    "WiFi Warning",
    "Wrench",
    "Wrench Screwdriver",
}


def icon_value(path: Path) -> str:
    name = path.stem
    if name.startswith("ic_fluent_"):
        name = name[len("ic_fluent_") :]
    name = name.removesuffix("_24_regular")
    name = name.removesuffix("_24_filled") + "_fill" if name.endswith("_24_filled") else name
    return name


def slug(value: str) -> str:
    return VALID_NAME_RE.sub("_", value.lower()).strip("_")


def enum_name(value: str) -> str:
    name = VALID_NAME_RE.sub("_", value).upper()
    if name[0].isdigit():
        name = f"ICON_{name}"
    return name


def themed_svg(svg: str, color: str) -> str:
    svg = FILL_RE.sub(f'fill="{color}"', svg)
    return STYLE_FILL_RE.sub(f"fill:{color}", svg)


def is_embedded_icon(path: Path) -> bool:
    return path.relative_to(ASSET_ROOT).parts[0] in EMBEDDED_ICON_NAMES


def main() -> None:
    svgs = sorted(ASSET_ROOT.rglob("SVG/*_24_regular.svg"))
    svgs += sorted(ASSET_ROOT.rglob("SVG/*_24_filled.svg"))
    svgs = [path for path in svgs if is_embedded_icon(path)]
    if not svgs:
        raise SystemExit(f"No SVG files found in {ASSET_ROOT}")

    value_counts: dict[str, int] = {}
    for source in svgs:
        value = icon_value(source)
        value_counts[value] = value_counts.get(value, 0) + 1

    BUILD_ROOT.mkdir(parents=True, exist_ok=True)
    for old in BUILD_ROOT.glob("*.svg"):
        old.unlink()

    members: dict[str, str] = {}
    qrc_files: list[tuple[str, str]] = []

    for source in svgs:
        value = icon_value(source)
        if value_counts[value] > 1:
            container = source.parent.parent.relative_to(ASSET_ROOT)
            container_slug = slug("_".join(container.parts))
            if container_slug != value.removesuffix("_fill"):
                value = f"{container_slug}_{value}"
        member = enum_name(value)
        if member in members:
            raise SystemExit(f"Duplicate UF4Icon member {member}: {source}")

        members[member] = value
        raw = source.read_text(encoding="utf-8")
        for suffix, color in (("black", "#212121"), ("white", "#FFFFFF")):
            target = BUILD_ROOT / f"{value}_{suffix}.svg"
            target.write_text(themed_svg(raw, color), encoding="utf-8", newline="\n")
            qrc_files.append((f"svg/{target.name}", target.name))

    qrc_lines = ['<RCC>', '  <qresource prefix="/uf4icons/icons">']
    qrc_lines.extend(
        f'    <file alias="{alias}">{name}</file>'
        for name, alias in sorted(qrc_files)
    )
    qrc_lines.extend(["  </qresource>", "</RCC>", ""])
    QRC_PATH.write_text("\n".join(qrc_lines), encoding="utf-8", newline="\n")

    member_width = max(len(name) for name in members)
    py_lines = [
        "# -*- coding: utf-8 -*-",
        '"""UF4 Fluent icon extension.',
        "",
        "This file is generated by Script/generate_uf4_icons.py.",
        '"""',
        "",
        "from enum import Enum",
        "from qfluentwidgets import FluentIconBase, Theme, getIconColor",
        "",
        "from . import uf4_icons_rc  # noqa: F401",
        "",
        "",
        "class UF4Icon(FluentIconBase, Enum):",
    ]
    py_lines.extend(
        f"    {name:<{member_width}} = {value!r}" for name, value in sorted(members.items())
    )
    py_lines.extend(
        [
            "",
            "    def path(self, theme=Theme.AUTO):",
            "        return f':/uf4icons/icons/{self.value}_{getIconColor(theme)}.svg'",
            "",
        ]
    )
    ICON_PY_PATH.write_text("\n".join(py_lines), encoding="utf-8", newline="\n")

    print(f"Generated {len(members)} UF4Icon members")
    print(f"Generated {len(qrc_files)} themed SVG resources")


if __name__ == "__main__":
    main()
